In [211]:
#importing libraries
import numpy as np
import pandas as pd
from scipy import stats

In [212]:
# for handling http requests
import requests

In [213]:
# for html parsing and web scraping
from bs4 import BeautifulSoup 
import bs4 as bs
import re
import urllib
from urllib.request import Request, urlopen

In [214]:
#webscraping
url = 'https://en.wikipedia.org/wiki/COVID-19_testing'

In [215]:
#read from url
html = urlopen(url) 
soup = BeautifulSoup(html, 'html.parser')

In [216]:
#read wikitables
tables = soup.find_all(id='wikitable')
covid_table = soup.findAll("table", { 'class' : 'wikitable' })

In [217]:
#As our data is in second table, read data from second table and load to Dataframe
df_table = pd.read_html(str(covid_table))

df_covid = df_table[1]
df_covid

,Country or region,Date[a],Tested,Units[b],Confirmed(cases),"Confirmed /tested,%","Tested /population,%","Confirmed /population,%",Ref.
0,Afghanistan,17 Dec 2020,154767,samples,49621,32.1,0.40,0.13,[258]
1,Albania,18 Feb 2021,428654,samples,96838,22.6,15.0,3.4,[259]
2,Algeria,2 Nov 2020,230553,samples,58574,25.4,0.53,0.13,[260][261]
3,Andorra,23 Feb 2022,300307,samples,37958,12.6,387,49.0,[262]
4,Angola,2 Feb 2021,399228,samples,20981,5.3,1.3,0.067,[263]
...,...,...,...,...,...,...,...,...,...
168,Venezuela,30 Mar 2021,3179074,samples,159149,5.0,11.0,0.55,[446]
169,Vietnam,28 Aug 2022,45772571,samples,11403302,24.9,46.4,11.6,[447]
170,Zambia,10 Mar 2022,3301860,samples,314850,9.5,19.0,1.8,[448]
171,Zimbabwe,3 Oct 2022,2517861,samples,257568,10.2,16.9,1.7,[260][449]
172,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...

# 1. Replace headers

Replaced headers to format which is easy to use in porgramming as the current headers some unwanted wordings which might even confuse the developer.

In [218]:
df_covid.rename(columns={'Country or region': 'country', 'Date[a]': 'date','Tested': 'tested', 'Units[b]': 'units','Confirmed(cases)':'confirmed_cases','Confirmed /tested,%':'percentage_confirmed','Tested /population,%':'percentage_tested','Confirmed /population,%':'percentage_confirmed_population'}, inplace=True)

In [219]:
df_covid

,country,date,tested,units,confirmed_cases,percentage_confirmed,percentage_tested,percentage_confirmed_population,Ref.
0,Afghanistan,17 Dec 2020,154767,samples,49621,32.1,0.40,0.13,[258]
1,Albania,18 Feb 2021,428654,samples,96838,22.6,15.0,3.4,[259]
2,Algeria,2 Nov 2020,230553,samples,58574,25.4,0.53,0.13,[260][261]
3,Andorra,23 Feb 2022,300307,samples,37958,12.6,387,49.0,[262]
4,Angola,2 Feb 2021,399228,samples,20981,5.3,1.3,0.067,[263]
...,...,...,...,...,...,...,...,...,...
168,Venezuela,30 Mar 2021,3179074,samples,159149,5.0,11.0,0.55,[446]
169,Vietnam,28 Aug 2022,45772571,samples,11403302,24.9,46.4,11.6,[447]
170,Zambia,10 Mar 2022,3301860,samples,314850,9.5,19.0,1.8,[448]
171,Zimbabwe,3 Oct 2022,2517861,samples,257568,10.2,16.9,1.7,[260][449]
172,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...

# 2. Drop Columns

As we have no value in having columns units and Ref, I will be dropping these columns. These columns doesnt add any value for your analysis.

In [220]:
df_covid = df_covid.drop(['units','Ref.'], axis=1)

In [221]:
df_covid

,country,date,tested,confirmed_cases,percentage_confirmed,percentage_tested,percentage_confirmed_population
0,Afghanistan,17 Dec 2020,154767,49621,32.1,0.40,0.13
1,Albania,18 Feb 2021,428654,96838,22.6,15.0,3.4
2,Algeria,2 Nov 2020,230553,58574,25.4,0.53,0.13
3,Andorra,23 Feb 2022,300307,37958,12.6,387,49.0
4,Angola,2 Feb 2021,399228,20981,5.3,1.3,0.067
...,...,...,...,...,...,...,...
168,Venezuela,30 Mar 2021,3179074,159149,5.0,11.0,0.55
169,Vietnam,28 Aug 2022,45772571,11403302,24.9,46.4,11.6
170,Zambia,10 Mar 2022,3301860,314850,9.5,19.0,1.8
171,Zimbabwe,3 Oct 2022,2517861,257568,10.2,16.9,1.7
172,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...,.mw-parser-output .reflist{font-size:90%;margi...

# 3. Drop Rows

As the last rows in the table of Wikipedia has the legend, we do not need that row for our analysis. I am dropping this last row.

In [222]:
df_covid = df_covid[:-1]

In [223]:
df_covid

,country,date,tested,confirmed_cases,percentage_confirmed,percentage_tested,percentage_confirmed_population
0,Afghanistan,17 Dec 2020,154767,49621,32.1,0.40,0.13
1,Albania,18 Feb 2021,428654,96838,22.6,15.0,3.4
2,Algeria,2 Nov 2020,230553,58574,25.4,0.53,0.13
3,Andorra,23 Feb 2022,300307,37958,12.6,387,49.0
4,Angola,2 Feb 2021,399228,20981,5.3,1.3,0.067
...,...,...,...,...,...,...,...
167,Uzbekistan,7 Sep 2020,2630000,43975,1.7,7.7,0.13
168,Venezuela,30 Mar 2021,3179074,159149,5.0,11.0,0.55
169,Vietnam,28 Aug 2022,45772571,11403302,24.9,46.4,11.6
170,Zambia,10 Mar 2022,3301860,314850,9.5,19.0,1.8
171,Zimbabwe,3 Oct 2022,2517861,257568,10.2,16.9,1.7

# 4.  Fix casing for columns with string data type

Converting the country name to upper case so that when we work 2 other datasets, it will be easy with merging the datasets based on country name

In [224]:
df_covid['country'] = df_covid['country'].str.upper()

/var/folders/p0/pjkt4x3j3x3fcxxknylhjcq00000gn/T/ipykernel_56940/2713194575.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_covid['country'] = df_covid['country'].str.upper()

In [225]:
df_covid

,country,date,tested,confirmed_cases,percentage_confirmed,percentage_tested,percentage_confirmed_population
0,AFGHANISTAN,17 Dec 2020,154767,49621,32.1,0.40,0.13
1,ALBANIA,18 Feb 2021,428654,96838,22.6,15.0,3.4
2,ALGERIA,2 Nov 2020,230553,58574,25.4,0.53,0.13
3,ANDORRA,23 Feb 2022,300307,37958,12.6,387,49.0
4,ANGOLA,2 Feb 2021,399228,20981,5.3,1.3,0.067
...,...,...,...,...,...,...,...
167,UZBEKISTAN,7 Sep 2020,2630000,43975,1.7,7.7,0.13
168,VENEZUELA,30 Mar 2021,3179074,159149,5.0,11.0,0.55
169,VIETNAM,28 Aug 2022,45772571,11403302,24.9,46.4,11.6
170,ZAMBIA,10 Mar 2022,3301860,314850,9.5,19.0,1.8
171,ZIMBABWE,3 Oct 2022,2517861,257568,10.2,16.9,1.7

# 5. Change data types of the columns

Changing data type of all the columns as we need to use this data to apply transformations. For now, this will help changing date format to YYYY-MM-dd.

In [226]:
df_covid = df_covid.astype({'date': 'datetime64', 'tested': 'int', 'confirmed_cases': 'int', 'percentage_confirmed': 'float', 'percentage_tested': 'float', 'percentage_confirmed_population': 'float'})

In [227]:
df_covid

,country,date,tested,confirmed_cases,percentage_confirmed,percentage_tested,percentage_confirmed_population
0,AFGHANISTAN,2020-12-17,154767,49621,32.1,0.40,0.130
1,ALBANIA,2021-02-18,428654,96838,22.6,15.00,3.400
2,ALGERIA,2020-11-02,230553,58574,25.4,0.53,0.130
3,ANDORRA,2022-02-23,300307,37958,12.6,387.00,49.000
4,ANGOLA,2021-02-02,399228,20981,5.3,1.30,0.067
...,...,...,...,...,...,...,...
167,UZBEKISTAN,2020-09-07,2630000,43975,1.7,7.70,0.130
168,VENEZUELA,2021-03-30,3179074,159149,5.0,11.00,0.550
169,VIETNAM,2022-08-28,45772571,11403302,24.9,46.40,11.600
170,ZAMBIA,2022-03-10,3301860,314850,9.5,19.00,1.800
171,ZIMBABWE,2022-10-03,2517861,257568,10.2,16.90,1.700

# 6. Identify outliers and bad data

Identifying the outliers is very important as this might lead to wrong results. Hence, applied data cleaning of identifying outliers. As this a public site, we can not trust the data quality.

In [228]:
df_covid_new = df_covid[
    (np.abs(stats.zscore(df_covid.select_dtypes(include=np.number))) > 3).all(axis=1)
]

In [229]:
df_covid

,country,date,tested,confirmed_cases,percentage_confirmed,percentage_tested,percentage_confirmed_population
0,AFGHANISTAN,2020-12-17,154767,49621,32.1,0.40,0.130
1,ALBANIA,2021-02-18,428654,96838,22.6,15.00,3.400
2,ALGERIA,2020-11-02,230553,58574,25.4,0.53,0.130
3,ANDORRA,2022-02-23,300307,37958,12.6,387.00,49.000
4,ANGOLA,2021-02-02,399228,20981,5.3,1.30,0.067
...,...,...,...,...,...,...,...
167,UZBEKISTAN,2020-09-07,2630000,43975,1.7,7.70,0.130
168,VENEZUELA,2021-03-30,3179074,159149,5.0,11.00,0.550
169,VIETNAM,2022-08-28,45772571,11403302,24.9,46.40,11.600
170,ZAMBIA,2022-03-10,3301860,314850,9.5,19.00,1.800
171,ZIMBABWE,2022-10-03,2517861,257568,10.2,16.90,1.700

# 7. Drop duplicates

Manually, with lesser data we might be able to identify the duplicates. But when we run this program regularly and the data gets updated and a case where we can find duplicates on nth day of program run, we can get bad results. So, I would like to handle it programatically.

In [209]:
df_covid = df_covid.drop_duplicates()

In [210]:
df_covid

,country,date,tested,confirmed_cases,percentage_confirmed,percentage_tested,percentage_confirmed_population
0,AFGHANISTAN,2020-12-17,154767,49621,32.1,0.40,0.130
1,ALBANIA,2021-02-18,428654,96838,22.6,15.00,3.400
2,ALGERIA,2020-11-02,230553,58574,25.4,0.53,0.130
3,ANDORRA,2022-02-23,300307,37958,12.6,387.00,49.000
4,ANGOLA,2021-02-02,399228,20981,5.3,1.30,0.067
...,...,...,...,...,...,...,...
167,UZBEKISTAN,2020-09-07,2630000,43975,1.7,7.70,0.130
168,VENEZUELA,2021-03-30,3179074,159149,5.0,11.00,0.550
169,VIETNAM,2022-08-28,45772571,11403302,24.9,46.40,11.600
170,ZAMBIA,2022-03-10,3301860,314850,9.5,19.00,1.800
171,ZIMBABWE,2022-10-03,2517861,257568,10.2,16.90,1.700

# Ethical Implications of Data Wrangling:

I have used COVID testings data from Wikipedia. Wikipedia is a public site and the data posted is visible to the public. Ethical implications of data wrangling of Wikipedia data:
    1. As we access data from the URL directly, this increases number of hits on the server which will have performance issues on the website.
    2. As public has access to update the data on Wikipedia, we can not consider this as trusted source and the data might not be upto date. This means the data being used might not be accurate.
    3. As there are multiple exceptions stated in the legend of the Wikitable, some of the countries data excluded few people or few areas of the country. This means numbers provided for few countries is not accurate.
    4. As we are performing some clean-up and transformations, we might change some data and data being used in our analysis might be slightly different from source data.
    
   As this is a public website, we shouldn't have any legal complications. However, the data wrangling from this source has implications of accuracy and performance issues on the website.

# Steps Completed:

I have completed below steps:
    1. Repalce Headers
    2. Drop Columns
    3. Drop Rows
    4. Fix casing for columns with string data type
    5. Change data types of the columns
    6. Identify outliers and bad data
    7. Drop duplicates